import bestSeller01 from '../images/best_seller_01.png';
import bestSeller02 from '../images/best_seller_02.png';
import bestSeller03 from '../images/best_seller_03.png';
import bestSeller04 from '../images/best_seller_04.png';
import bestSeller05 from '../images/best_seller_05.png';

export const bestSellerData = [
    { 
    id: 46, 
    title: '우롱티 + 코코넛 + 밀크폼', 
    description: '깊고 고소한 우롱차에 코코넛 젤리와 달콤짭쪼름한 밀크폼을 올려 다양한 식감과 함께 부드럽게 즐기는 오리지널티', 
    image: bestSeller01, 
    L_price: 'Large 4,700원',
    J_price: 'Jumbo 6,100원',
    L_kcal: '145kcal',
    J_kcal: '201kcal',
    warning: '* 알레르기 유발 식품 : 우유, 대두',
    L_size:'473ml',
    L_sugar:'12g',
    L_protein:'1g',
    L_fat: '6g',
    L_natrium: '136mg',
    L_caffeine: '65mg',
    J_size:'651ml',
    J_sugar:'18g',
    J_protein:'1g',
    J_fat: '7g',
    J_natrium: '181mg',
    J_caffeine: '86ml',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 47, 
    title: '우롱티 + 코코넛 + 밀크폼 (HOT)', 
    description: '깊고 고소한 우롱차에 코코넛 젤리와 달콤짭쪼름한 밀크폼을 올려 다양한 식감과 함께 부드럽게 즐기는 오리지널티', 
    image: bestSeller01, 
    L_price: 'Large 4,700원',
    J_price: 'Jumbo 6,100원',
    L_kcal: '145kcal',
    J_kcal: '201kcal',
    warning: '* 알레르기 유발 식품 : 우유, 대두',
    L_size:'413ml',
    L_sugar:'12g',
    L_protein:'1g',
    L_fat: '6g',
    L_natrium: '138mg',
    L_caffeine: '78mg',
    J_size:'473ml',
    J_sugar:'18g',
    J_protein:'1g',
    J_fat: '7g',
    J_natrium: '184mg',
    J_caffeine: '99ml',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 48, 
    title: '초콜렛 밀크티 + 밀크폼', 
    description: '부드러운 밀크에 녹아든 진한 초콜렛을 느낄 수 있는 초콜렛 밀크티와 달콤짭쪼름한 밀크폼', 
    image: bestSeller02, 
    L_price: 'Large 4,700원',
    J_price: 'Jumbo 5,900원',
    L_kcal: '341kcal',
    J_kcal: '435kcal',
    warning: '* 알레르기 유발 식품 : 우유, 대두',
    L_size:'473ml',
    L_sugar:'2g',
    L_protein:'5g',
    L_fat: '16g',
    L_natrium: '183mg',
    L_caffeine: '12mg',
    J_size:'414ml',
    J_sugar:'2g',
    J_protein:'7g',
    J_fat: '20g',
    J_natrium: '201mg',
    J_caffeine: '17ml',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 49, 
    title: '초콜렛 밀크티 + 밀크폼 (HOT)', 
    description: '부드러운 밀크에 녹아든 진한 초콜렛을 느낄 수 있는 초콜렛 밀크티와 달콤짭쪼름한 밀크폼', 
    image: bestSeller02, 
    L_price: 'Large 4,700원',
    J_price: 'Jumbo 6,100원',
    L_kcal: '435kcal',
    J_kcal: '484kcal',
    warning: '* 알레르기 유발 식품 : 우유, 대두',
    L_size:'414ml',
    L_sugar:'2g',
    L_protein:'7g',
    L_fat: '20g',
    L_natrium: '202mg',
    L_caffeine: '16mg',
    J_size:'473ml',
    J_sugar:'2g',
    J_protein:'7g',
    J_fat: '22g',
    J_natrium: '212mg',
    J_caffeine: '19ml',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 50, 
    title: '블랙 밀크티 + 펄', 
    description: '공차 대표 메뉴 블랙밀크티와 쫄깃쫄깃한 펄의 콤비네이션', 
    image: bestSeller03, 
    L_price: 'Large 4,700원',
    J_price: 'Jumbo 5,900원',
    L_kcal: '277kcal',
    J_kcal: '378kcal',
    warning: '* 알레르기 유발 식품 : 우유, 이산화황',
    L_size:'473ml',
    L_sugar:'7g',
    L_protein:'1g',
    L_fat: '9g',
    L_natrium: '59mg',
    L_caffeine: '107mg',
    J_size:'651ml',
    J_sugar:'10g',
    J_protein:'2g',
    J_fat: '13g',
    J_natrium: '81mg',
    J_caffeine: '147ml',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 51, 
    title: '블랙 밀크티 + 펄 (HOT)', 
    description: '공차 대표 메뉴 블랙밀크티와 쫄깃쫄깃한 펄의 콤비네이션', 
    image: bestSeller03, 
    L_price: 'Large 4,700원',
    J_price: 'Jumbo 5,900원',
    L_kcal: '202kcal',
    J_kcal: '246kcal',
    warning: '* 알레르기 유발 식품 : 우유, 이산화황',
    L_size:'414ml',
    L_sugar:'9g',
    L_protein:'6g',
    L_fat: '4g',
    L_natrium: '72mg',
    L_caffeine: '104mg',
    J_size:'651ml',
    J_sugar:'11g',
    J_protein:'7g',
    J_fat: '4.6g',
    J_natrium: '83mg',
    J_caffeine: '118ml',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 52, 
    title: '망고 요구르트 + 화이트펄', 
    description: '달콤한 망고 과육과 요구르트에 화이트펄의 꼬들꼬들함이 느껴지는 주스', 
    image: bestSeller04, 
    L_price: 'Large 5,200원',
    J_price: 'Jumbo 5,900원',
    L_kcal: '202kcal',
    J_kcal: '289kcal',
    warning: '* 알레르기 유발 식품 : 우유, 대두',
    L_size:'473ml',
    L_sugar:'40g',
    L_protein:'1g',
    L_fat: '0g',
    L_natrium: '33mg',
    L_caffeine: '0mg',
    J_size:'651ml',
    J_sugar:'57g',
    J_protein:'1g',
    J_fat: '0g',
    J_natrium: '46mg',
    J_caffeine: '0mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 53, 
    title: '딸기 쿠키 스무디 + 펄', 
    description: '얼그레이티로 만든 밀크 스무디에 달콤한 딸기와 바삭한 쿠키를 더한 스무디와 쫄깃쫄깃한 펄', 
    image: bestSeller05, 
    L_price: 'Large 5,900원',
    L_kcal: '528kcal',
    warning: '* 알레르기 유발 식품 : 우유, 대두, 밀, 이산화황',
    L_size:'473ml',
    L_sugar:'60g',
    L_protein:'4g',
    L_fat: '11g',
    L_natrium: '118mg',
    L_caffeine: '21mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
];