import coffee01 from '../images/coffee_01.png';
import coffee02 from '../images/coffee_02.png';
import coffee03 from '../images/coffee_03.png';
import coffee04 from '../images/coffee_04.png';
import coffee05 from '../images/coffee_05.png';

export const coffeeData = [
{ 
    id: 112, 
    title: '얼그레이 아메리카노', 
    description: '공차 시그니처 블렌딩 원두와 향긋한 얼그레이티의 조화가 좋은 스페셜 커피 메뉴', 
    image: coffee01, 
    L_price: 'Large 4,200원',
    J_price: 'Jumbo 4,700원',
    L_kcal: '13kcal',
    J_kcal: '18kcal',
    warning: '',
    L_size:'473ml',
    L_sugar:'20g',
    L_protein:'1g',
    L_fat: '0g',
    L_natrium: '1mg',
    L_caffeine: '143mg',
    J_size:'651ml',
    J_sugar:'27g',
    J_protein:'1g',
    J_fat: '0g',
    J_natrium: '1mg',
    J_caffeine: '220mg',
    isLargeAvailable: true,
    isJumboAvailable: true
},
    { 
    id: 113, 
    title: '얼그레이 아메리카노 (HOT)', 
    description: '공차 시그니처 블렌딩 원두와 향긋한 얼그레이티의 조화가 좋은 스페셜 커피 메뉴', 
    image: coffee01, 
    L_price: 'Large 4,500원',
    J_price: 'Jumbo 5,600원',
    L_kcal: '13kcal',
    J_kcal: '15kcal',
    warning: '',
    L_size:'414ml',
    L_sugar:'20g',
    L_protein:'0g',
    L_fat: '0g',
    L_natrium: '3mg',
    L_caffeine: '147mg',
    J_size:'473ml',
    J_sugar:'27	g',
    J_protein:'0g',
    J_fat: '0g',
    J_natrium: '3mg',
    J_caffeine: '186mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 114, 
    title: '카페 모카', 
    description: '진한 커피에 공차 초콜렛을 더하고 달콤짭조름한 밀크폼과 함께 즐기는 공차만의 커피 음료', 
    image: coffee02, 
    L_price: 'Large 4,500원',
    J_price: 'Jumbo 5,600원',
    L_kcal: '310kcal',
    J_kcal: '426kcal',
    warning: '* 알레르기 유발 식품 : 우유',
    L_size:'473ml',
    L_sugar:'8g',
    L_protein:'9g',
    L_fat: '13g',
    L_natrium: '245mg',
    L_caffeine: '148mg',
    J_size:'651ml',
    J_sugar:'11g',
    J_protein:'12g',
    J_fat: '18g',
    J_natrium: '337mg',
    J_caffeine: '219mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 115, 
    title: '카페 모카 (HOT)', 
    description: '진한 커피에 공차 초콜렛을 더하고 달콤짭조름한 밀크폼과 함께 즐기는 공차만의 커피 음료', 
    image: coffee02, 
    L_price: 'Large 4,500원',
    J_price: 'Jumbo 5,600원',
    L_kcal: '422kcal',
    J_kcal: '482kcal',
    warning: '',
    L_size:'414ml',
    L_sugar:'12g',
    L_protein:'12g',
    L_fat: '19g',
    L_natrium: '329mg',
    L_caffeine: '165mg',
    J_size:'473ml',
    J_sugar:'13g',
    J_protein:'13g',
    J_fat: '21g',
    J_natrium: '376mg',
    J_caffeine: '200mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 116, 
    title: '아메리카노', 
    description: '브라질, 콜롬비아 외 대표적인 원두 5가지를 블렌딩하여 찾은 최적의 맛', 
    image: coffee03, 
    L_price: 'Large 3,700원',
    J_price: 'Jumbo 4,200원',
    L_kcal: '5kcal',
    J_kcal: '7kcal',
    warning: '',
    L_size:'473ml',
    L_sugar:'0g',
    L_protein:'9g',
    L_fat: '0g',
    L_natrium: '3mg',
    L_caffeine: '102mg',
    J_size:'651ml',
    J_sugar:'0g',
    J_protein:'0g',
    J_fat: '0g',
    J_natrium: '4mg',
    J_caffeine: '185mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 117, 
    title: '아메리카노 (HOT)', 
    description: '브라질, 콜롬비아 외 대표적인 원두 5가지를 블렌딩하여 찾은 최적의 맛', 
    image: coffee03, 
    L_price: 'Large 3,700원',
    J_price: 'Jumbo 4,200원',
    L_kcal: '5kcal',
    J_kcal: '5kcal',
    warning: '',
    L_size:'414ml',
    L_sugar:'0g',
    L_protein:'0g',
    L_fat: '0g',
    L_natrium: '5mg',
    L_caffeine: '119mg',
    J_size:'473ml',
    J_sugar:'0g',
    J_protein:'0g',
    J_fat: '0g',
    J_natrium: '6mg',
    J_caffeine: '209mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 118, 
    title: '카페라떼', 
    description: '진하고 부드러운 공차의 새로운 커피 (HOT / ICED)​', 
    image: coffee04, 
    L_price: 'Large 4,200원',
    J_price: 'Jumbo 5,300원',
    L_kcal: '132kcal',
    J_kcal: '182kcal',
    warning: '*알레르기 유발 식품 : 우유',
    L_size:'473ml',
    L_sugar:'9g',
    L_protein:'7g',
    L_fat: '4.3g',
    L_natrium: '82mg',
    L_caffeine: '78mg',
    J_size:'651ml',
    J_sugar:'12g',
    J_protein:'10g',
    J_fat: '6g',
    J_natrium: '113mg',
    J_caffeine: '199mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 119, 
    title: '카페라떼 (HOT)', 
    description: '진하고 부드러운 공차의 새로운 커피 (HOT / ICED)​', 
    image: coffee04, 
    L_price: 'Large 3,700원',
    J_price: 'Jumbo 4,200원',
    L_kcal: '224kcal',
    J_kcal: '225kcal',
    warning: '*알레르기 유발 식품 : 우유',
    L_size:'414ml',
    L_sugar:'13g',
    L_protein:'11g',
    L_fat: '7g',
    L_natrium: '135mg',
    L_caffeine: '109mg',
    J_size:'473ml',
    J_sugar:'15g',
    J_protein:'13g',
    J_fat: '8g',
    J_natrium: '154mg',
    J_caffeine: '236mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 120, 
    title: '바닐라 카페라떼', 
    description: '진한 커피에 마다가스카르산 바닐라빈이 더해져 달콤하고 깊은 풍미를 느낄 수 있는 공차만의 커피 음료', 
    image: coffee05, 
    L_price: 'Large 4,500원',
    J_price: 'Jumbo 5,600원',
    L_kcal: '232kcal',
    J_kcal: '320kcal',
    warning: '*알레르기 유발 식품 : 우유, 대두',
    L_size:'473ml',
    L_sugar:'24g',
    L_protein:'8g',
    L_fat: '5g',
    L_natrium: '99mg',
    L_caffeine: '87mg',
    J_size:'651ml',
    J_sugar:'33g',
    J_protein:'11g',
    J_fat: '7g',
    J_natrium: '136mg',
    J_caffeine: '204mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 121, 
    title: '공차슈페너', 
    description: '향긋한 얼그레이티를 넣은 공차만의 블렌딩 아메리카노에 달콤짭조름한 밀크폼을 얹은 스페셜 메뉴', 
    image: coffee05, 
    L_price: 'Large 4,300원',
    L_kcal: '149kcal',
    warning: '* 알레르기 유발 식품 : 우유, 대두',
    L_size:'473ml',
    L_sugar:'7g',
    L_protein:'1g',
    L_fat: '6g',
    L_natrium: '106mg',
    L_caffeine: '130mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    }
]