import fruitTea01 from '../images/fruit_tea_01.png';
import fruitTea02 from '../images/fruit_tea_02.png';
import fruitTea03 from '../images/fruit_tea_03.png';
import fruitTea04 from '../images/fruit_tea_04.png';
import fruitTea05 from '../images/fruit_tea_05.png';
import fruitTea06 from '../images/fruit_tea_06.png';
import fruitTea07 from '../images/fruit_tea_07.png';
import fruitTea08 from '../images/fruit_tea_08.png';
import fruitTea09 from '../images/fruit_tea_09.png';
import fruitTea10 from '../images/fruit_tea_10.png';

export const fruitTeaData = [
{ 
    id: 94, 
    title: '망고 요구르트', 
    description: '농축된 달콤한 망고의 입자와 새콤한 요구르트의 조합, 망고 요구르트', 
    image: fruitTea01, 
    L_price: 'Large 5,000원',
    J_price: 'Jumbo 6,100원',
    L_kcal: '170kcal',
    J_kcal: '234kcal',
    warning: '* 알레르기 유발 식품 : 우유, 대두',
    L_size:'473ml',
    L_sugar:'31g',
    L_protein:'1g',
    L_fat: '0g',
    L_natrium: '28mg',
    L_caffeine: '0mg',
    J_size:'651ml',
    J_sugar:'43g',
    J_protein:'1g',
    J_fat: '0g',
    J_natrium: '38mg',
    J_caffeine: '0mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 95, 
    title: '자몽 요구르트', 
    description: '달콤하고 쌉싸름한 자몽과 새콤한 요구르트의 조합', 
    image: fruitTea02, 
    L_price: 'Large 5,000원',
    J_price: 'Jumbo 6,100원',
    L_kcal: '146kcal',
    J_kcal: '201kcal',
    warning: '* 알레르기 유발 식품 : 우유, 대두',
    L_size:'473ml',
    L_sugar:'27g',
    L_protein:'1g',
    L_fat: '0g',
    L_natrium: '21mg',
    L_caffeine: '0mg',
    J_size:'651ml',
    J_sugar:'38g',
    J_protein:'1g',
    J_fat: '0g',
    J_natrium: '29mg',
    J_caffeine: '0mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 96, 
    title: '망고 주스', 
    description: '농축된 달콤한 망고의 입자가 느껴지는 달콤한 망고 주스', 
    image: fruitTea03, 
    L_price: 'Large 4,600원',
    J_price: 'Jumbo 5,700원',
    L_kcal: '130kcal',
    J_kcal: '179kcal',
    warning: '',
    L_size:'473ml',
    L_sugar:'24g',
    L_protein:'0g',
    L_fat: '0g',
    L_natrium: '24mg',
    L_caffeine: '0mg',
    J_size:'651ml',
    J_sugar:'33g',
    J_protein:'1g',
    J_fat: '0g',
    J_natrium: '33mg',
    J_caffeine: '0mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 97, 
    title: '자스민 요구르트', 
    description: '향긋한 자스민티에 새콤달콤한 요구르트의 조합', 
    image: fruitTea04, 
    L_price: 'Large 5,000원',
    J_price: 'Jumbo 6,100원',
    L_kcal: '145kcal',
    J_kcal: '200kcal',
    warning: '',
    L_size:'473ml',
    L_sugar:'29g',
    L_protein:'2g',
    L_fat: '0g',
    L_natrium: '22mg',
    L_caffeine: '139mg',
    J_size:'651ml',
    J_sugar:'40g',
    J_protein:'3g',
    J_fat: '0g',
    J_natrium: '30mg',
    J_caffeine: '171mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 98, 
    title: '레몬 자스민티', 
    description: '상큼한 레몬 베이스와 로즈마리가 만드는 새로운 하모니의 자스민 과일 티', 
    image: fruitTea05, 
    L_price: 'Large 4,800원',
    J_price: 'Jumbo 5,900원',
    L_kcal: '162kcal',
    J_kcal: '223kcal',
    warning: '',
    L_size:'473ml',
    L_sugar:'34g',
    L_protein:'1g',
    L_fat: '0g',
    L_natrium: '18mg',
    L_caffeine: '175mg',
    J_size:'651ml',
    J_sugar:'46g',
    J_protein:'1g',
    J_fat: '0g',
    J_natrium: '24mg',
    J_caffeine: '210mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 99, 
    title: '레몬 자스민티 (HOT)', 
    description: '상큼한 레몬 베이스와 로즈마리가 만드는 새로운 하모니의 자스민 과일 티', 
    image: fruitTea05, 
    L_price: 'Large 4,500원',
    J_price: 'Jumbo 5,600원',
    L_kcal: '131kcal',
    J_kcal: '149kcal',
    warning: '',
    L_size:'414ml',
    L_sugar:'28g',
    L_protein:'1g',
    L_fat: '0g',
    L_natrium: '16mg',
    L_caffeine: '201mg',
    J_size:'473ml',
    J_sugar:'32g',
    J_protein:'1g',
    J_fat: '0g',
    J_natrium: '18mg',
    J_caffeine: '241mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 100, 
    title: '레몬 요구르트', 
    description: '상큼한 레몬 베이스에 새콤달콤한 요구르트의 조합', 
    image: fruitTea06, 
    L_price: 'Large 5,000원',
    J_price: 'Jumbo 6,100원',
    L_kcal: '182kcal',
    J_kcal: '250kcal',
    warning: '* 알레르기 유발 식품 : 우유, 대두',
    L_size:'473ml',
    L_sugar:'38g',
    L_protein:'2g',
    L_fat: '0g',
    L_natrium: '19mg',
    L_caffeine: '0mg',
    J_size:'651ml',
    J_sugar:'52g',
    J_protein:'2g',
    J_fat: '0g',
    J_natrium: '26mg',
    J_caffeine: '0mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 101, 
    title: '자몽 자스민티', 
    description: '달콤하고 쌉싸름한 자몽과 로즈마리가 만드는 새로운 하모니의 자스민 과일 티', 
    image: fruitTea07, 
    L_price: 'Large 4,800원',
    J_price: 'Jumbo 5,900원',
    L_kcal: '58kcal',
    J_kcal: '80kcal',
    warning: '',
    L_size:'473ml',
    L_sugar:'11g',
    L_protein:'1g',
    L_fat: '0g',
    L_natrium: '4mg',
    L_caffeine: '64mg',
    J_size:'651ml',
    J_sugar:'15g',
    J_protein:'1g',
    J_fat: '0g',
    J_natrium: '5mg',
    J_caffeine: '85mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 102, 
    title: '자몽 자스민티 (HOT)', 
    description: '달콤하고 쌉싸름한 자몽과 로즈마리가 만드는 새로운 하모니의 자스민 과일 티', 
    image: fruitTea07, 
    L_price: 'Large 4,500원',
    J_price: 'Jumbo 5,600원',
    L_kcal: '69kcal',
    J_kcal: '79kcal',
    warning: '',
    L_size:'414ml',
    L_sugar:'14g',
    L_protein:'1g',
    L_fat: '0g',
    L_natrium: '32mg',
    L_caffeine: '64mg',
    J_size:'473ml',
    J_sugar:'16g',
    J_protein:'1g',
    J_fat: '0g',
    J_natrium: '36mg',
    J_caffeine: '85mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 103, 
    title: '청포도 자스민티', 
    description: '쌉싸름한 자스민티에 상큼한 청포도 넣어 청량하고 달콤한 자스민 과일 티', 
    image: fruitTea08, 
    L_price: 'Large 4,800원',
    J_price: 'Jumbo 5,900원',
    L_kcal: '137kcal',
    J_kcal: '189kcal',
    warning: '',
    L_size:'473ml',
    L_sugar:'28g',
    L_protein:'1g',
    L_fat: '0g',
    L_natrium: '5mg',
    L_caffeine: '64mg',
    J_size:'651ml',
    J_sugar:'38g',
    J_protein:'1g',
    J_fat: '0g',
    J_natrium: '7mg',
    J_caffeine: '85mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 104, 
    title: '청포도 자스민티 (HOT)', 
    description: '쌉싸름한 자스민티에 상큼한 청포도 넣어 청량하고 달콤한 자스민 과일 티', 
    image: fruitTea08, 
    L_price: 'Large 4,500원',
    J_price: 'Jumbo 5,600원',
    L_kcal: '109kcal',
    J_kcal: '124kcal',
    warning: '',
    L_size:'414ml',
    L_sugar:'22g',
    L_protein:'1g',
    L_fat: '0g',
    L_natrium: '6mg',
    L_caffeine: '64mg',
    J_size:'473ml',
    J_sugar:'25g',
    J_protein:'1g',
    J_fat: '0g',
    J_natrium: '7mg',
    J_caffeine: '85mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 105, 
    title: '패션 프룻 히비스커스', 
    description: '새콤달콤한 패션 프룻&히비스커스의 조화가 돋보이는 카페인 Free 티', 
    image: fruitTea09, 
    L_price: 'Large 4,800원',
    J_price: 'Jumbo 5,900원',
    L_kcal: '106kcal',
    J_kcal: '146kcal',
    warning: '',
    L_size:'473ml',
    L_sugar:'20g',
    L_protein:'1g',
    L_fat: '0g',
    L_natrium: '8mg',
    L_caffeine: '0mg',
    J_size:'651ml',
    J_sugar:'27g',
    J_protein:'1g',
    J_fat: '0g',
    J_natrium: '11mg',
    J_caffeine: '0mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 106, 
    title: '패션 프룻 히비스커스 (HOT)', 
    description: '새콤달콤한 패션 프룻&히비스커스의 조화가 돋보이는 카페인 Free 티', 
    image: fruitTea09, 
    L_price: 'Large 4,500원',
    J_price: 'Jumbo 5,600원',
    L_kcal: '106kcal',
    J_kcal: '146kcal',
    warning: '',
    L_size:'414ml',
    L_sugar:'20g',
    L_protein:'0g',
    L_fat: '0g',
    L_natrium: '8mg',
    L_caffeine: '0mg',
    J_size:'473ml',
    J_sugar:'27	g',
    J_protein:'0g',
    J_fat: '0g',
    J_natrium: '11mg',
    J_caffeine: '0mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 107, 
    title: '자몽 주스', 
    description: '달콤하고 쌉싸름한 자몽의 입자가 느껴지는 달콤한 자몽 주스', 
    image: fruitTea10, 
    L_price: 'Large 5,700원',
    L_kcal: '386kcal',
    warning: '* 알레르기 유발 식품 : 우유, 대두',
    L_size:'473ml',
    L_sugar:'41g',
    L_protein:'1g',
    L_fat: '9g',
    L_natrium: '96mg',
    L_caffeine: '0mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
] 