import milkTea01 from '../images/milk_tea_01.png';
import milkTea02 from '../images/milk_tea_02.png';
import milkTea03 from '../images/milk_tea_03.png';
import milkTea04 from '../images/milk_tea_04.png';
import milkTea05 from '../images/milk_tea_05.png';
import milkTea06 from '../images/milk_tea_06.png';
import milkTea07 from '../images/milk_tea_07.png';
import milkTea08 from '../images/milk_tea_08.png';
import milkTea09 from '../images/milk_tea_09.png';

export const milkTeaData = [
    { 
    id: 54, 
    title: '블랙 밀크티', 
    description: '진한 향과 맛을 느낄 수 있는 블랙티(홍차)와 밀크의 만남 (HOT / ICED)​', 
    image: milkTea01, 
    L_price: 'Large 4,500원',
    J_price: 'Jumbo 5,600원',
    L_kcal: '195kcal',
    J_kcal: '269kcal',
    warning: '* 알레르기 유발 식품 : 우유',
    L_size:'473ml',
    L_sugar:'1g',
    L_protein:'1g',
    L_fat: '9g',
    L_natrium: '53mg',
    L_caffeine: '100mg',
    J_size:'651ml',
    J_sugar:'2g',
    J_protein:'2g',
    J_fat: '13g',
    J_natrium: '73mg',
    J_caffeine: '128mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 55, 
    title: '블랙 밀크티 (HOT)', 
    description: '진한 향과 맛을 느낄 수 있는 블랙티(홍차)와 밀크의 만남 (HOT / ICED)​', 
    image: milkTea01, 
    L_price: 'Large 4,500원',
    J_price: 'Jumbo 5,600원',
    L_kcal: '120kcal',
    J_kcal: '137kcal',
    warning: '* 알레르기 유발 식품 : 우유',
    L_size:'414ml',
    L_sugar:'3g',
    L_protein:'6g',
    L_fat: '4g',
    L_natrium: '65mg',
    L_caffeine: '84mg',
    J_size:'473ml',
    J_sugar:'4g',
    J_protein:'7g',
    J_fat: '4.6g',
    J_natrium: '75mg',
    J_caffeine: '95mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 56, 
    title: '얼그레이 밀크티', 
    description: '베르가못 향의 얼그레이티(홍차)와 밀크가 부드러운 조화를 이루는 밀크티 (HOT / ICED)​', 
    image: milkTea02, 
    L_price: 'Large 4,500원',
    J_price: 'Jumbo 5,600원',
    L_kcal: '198kcal',
    J_kcal: '272kcal',
    warning: '* 알레르기 유발 식품 : 우유',
    L_size:'473ml',
    L_sugar:'1g',
    L_protein:'1g',
    L_fat: '10g',
    L_natrium: '50mg',
    L_caffeine: '116mg',
    J_size:'651ml',
    J_sugar:'2g',
    J_protein:'2g',
    J_fat: '13g',
    J_natrium: '68mg',
    J_caffeine: '148mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 57, 
    title: '얼그레이 밀크티 (HOT)', 
    description: '베르가못 향의 얼그레이티(홍차)와 밀크가 부드러운 조화를 이루는 밀크티 (HOT / ICED)​', 
    image: milkTea02, 
    L_price: 'Large 4,500원',
    J_price: 'Jumbo 5,600원',
    L_kcal: '198kcal',
    J_kcal: '272kcal',
    warning: '* 알레르기 유발 식품 : 우유',
    L_size:'414ml',
    L_sugar:'2g',
    L_protein:'5g',
    L_fat: '3.4g',
    L_natrium: '58mg',
    L_caffeine: '97mg',
    J_size:'473ml',
    J_sugar:'3g',
    J_protein:'6g',
    J_fat: '3.9g',
    J_natrium: '67mg',
    J_caffeine: '110mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 58, 
    title: '우롱 밀크티', 
    description: '묵직하고 깊은 향의 우롱차에 밀크가 더해진 우롱밀크티 (HOT / ICED)​', 
    image: milkTea03, 
    L_price: 'Large 4,500원',
    J_price: 'Jumbo 5,600원',
    L_kcal: '154kcal',
    J_kcal: '212kcal',
    warning: '* 알레르기 유발 식품 : 우유',
    L_size:'473ml',
    L_sugar:'1g',
    L_protein:'1g',
    L_fat: '8g',
    L_natrium: '38mg',
    L_caffeine: '78mg',
    J_size:'651ml',
    J_sugar:'1g',
    J_protein:'1g',
    J_fat: '11g',
    J_natrium: '52mg',
    J_caffeine: '99mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 59, 
    title: '우롱 밀크티 (HOT)', 
    description: '묵직하고 깊은 향의 우롱차에 밀크가 더해진 우롱밀크티 (HOT / ICED)​', 
    image: milkTea03, 
    L_price: 'Large 4,500원',
    J_price: 'Jumbo 5,600원',
    L_kcal: '106kcal',
    J_kcal: '121kcal',
    warning: '* 알레르기 유발 식품 : 우유',
    L_size:'414ml',
    L_sugar:'2g',
    L_protein:'5g',
    L_fat: '3.5g',
    L_natrium: '59mg',
    L_caffeine: '65mg',
    J_size:'473ml',
    J_sugar:'3g',
    J_protein:'6g',
    J_fat: '4g',
    J_natrium: '67mg',
    J_caffeine: '73mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 60, 
    title: '초콜렛 밀크티', 
    description: '부드러운 밀크에 녹아든 진한 초콜렛을 느낄 수 있는 초콜렛 밀크티 (HOT / ICED)', 
    image: milkTea04, 
    L_price: 'Large 4,500원',
    J_price: 'Jumbo 5,600원',
    L_kcal: '249kcal',
    J_kcal: '343kcal',
    warning: '* 알레르기 유발 식품 : 우유',
    L_size:'473ml',
    L_sugar:'1g',
    L_protein:'4g',
    L_fat: '11g',
    L_natrium: '49mg',
    L_caffeine: '12mg',
    J_size:'651ml',
    J_sugar:'1g',
    J_protein:'6g',
    J_fat: '15g',
    J_natrium: '67mg',
    J_caffeine: '17mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 61, 
    title: '초콜렛 밀크티 (HOT)', 
    description: '부드러운 밀크에 녹아든 진한 초콜렛을 느낄 수 있는 초콜렛 밀크티 (HOT / ICED)', 
    image: milkTea04, 
    L_price: 'Large 4,500원',
    J_price: 'Jumbo 5,600원',
    L_kcal: '343kcal',
    J_kcal: '392kcal',
    warning: '* 알레르기 유발 식품 : 우유',
    L_size:'414ml',
    L_sugar:'1g',
    L_protein:'6g',
    L_fat: '15g',
    L_natrium: '67mg',
    L_caffeine: '16mg',
    J_size:'473ml',
    J_sugar:'2g',
    J_protein:'7g',
    J_fat: '17g',
    J_natrium: '77mg',
    J_caffeine: '19mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 62, 
    title: '자스민 밀크티', 
    description: '향긋한 꽃 향이 느껴지는 자스민티를 부드럽게 즐기는 밀크티', 
    image: milkTea05, 
    L_price: 'Large 4,500원',
    J_price: 'Jumbo 5,600원',
    L_kcal: '183kcal',
    J_kcal: '252kcal',
    warning: '* 알레르기 유발 식품 : 우유',
    L_size:'473ml',
    L_sugar:'1g',
    L_protein:'1g',
    L_fat: '9g',
    L_natrium: '45mg',
    L_caffeine: '97mg',
    J_size:'651ml',
    J_sugar:'1g',
    J_protein:'2g',
    J_fat: '12g',
    J_natrium: '62mg',
    J_caffeine: '124mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 63, 
    title: '자스민 밀크티 (HOT)', 
    description: '향긋한 꽃 향이 느껴지는 자스민티를 부드럽게 즐기는 밀크티', 
    image: milkTea05, 
    L_price: 'Large 4,500원',
    J_price: 'Jumbo 5,600원',
    L_kcal: '107kcal',
    J_kcal: '122kcal',
    warning: '* 알레르기 유발 식품 : 우유',
    L_size:'414ml',
    L_sugar:'3g',
    L_protein:'5g',
    L_fat: '3.1g',
    L_natrium: '57mg',
    L_caffeine: '81mg',
    J_size:'473ml',
    J_sugar:'3g',
    J_protein:'6g',
    J_fat: '3.6g',
    J_natrium: '65mg',
    J_caffeine: '92mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 64, 
    title: '타로 밀크티', 
    description: '타로의 고소함과 밀크의 조합 (HOT / ICED)​', 
    image: milkTea06, 
    L_price: 'Large 4,500원',
    J_price: 'Jumbo 5,600원',
    L_kcal: '297kcal',
    J_kcal: '408kcal',
    warning: '* 알레르기 유발 식품 : 우유',
    L_size:'473ml',
    L_sugar:'6g',
    L_protein:'1g',
    L_fat: '12g',
    L_natrium: '71mg',
    L_caffeine: '0mg',
    J_size:'651ml',
    J_sugar:'9g',
    J_protein:'2g',
    J_fat: '17g',
    J_natrium: '97mg',
    J_caffeine: '0mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 65, 
    title: '타로 밀크티 (HOT)', 
    description: '타로의 고소함과 밀크의 조합 (HOT / ICED)​', 
    image: milkTea06, 
    L_price: 'Large 4,500원',
    J_price: 'Jumbo 5,600원',
    L_kcal: '394kcal',
    J_kcal: '450kcal',
    warning: '* 알레르기 유발 식품 : 우유',
    L_size:'414ml',
    L_sugar:'9g',
    L_protein:'1g',
    L_fat: '17g',
    L_natrium: '94mg',
    L_caffeine: '0mg',
    J_size:'473ml',
    J_sugar:'10g',
    J_protein:'2g',
    J_fat: '19g',
    J_natrium: '107mg',
    J_caffeine: '0mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 66, 
    title: '제주 그린 밀크티', 
    description: '제주 녹차를 사용하여 쌉싸름한 맛과 달콤한 맛이 어우러진 밀크티', 
    image: milkTea07, 
    L_price: 'Large 4,500원',
    J_price: 'Jumbo 5,600원',
    L_kcal: '184kcal',
    J_kcal: '254kcal',
    warning: '* 알레르기 유발 식품 : 우유',
    L_size:'473ml',
    L_sugar:'16g',
    L_protein:'7g',
    L_fat: '4g',
    L_natrium: '83mg',
    L_caffeine: '49mg',
    J_size:'651ml',
    J_sugar:'22g',
    J_protein:'10g',
    J_fat: '6g',
    J_natrium: '114mg',
    J_caffeine: '67mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 67, 
    title: '제주 그린 밀크티 (HOT)', 
    description: '제주 녹차를 사용하여 쌉싸름한 맛과 달콤한 맛이 어우러진 밀크티', 
    image: milkTea07, 
    L_price: 'Large 4,500원',
    J_price: 'Jumbo 5,600원',
    L_kcal: '294kcal',
    J_kcal: '336kcal',
    warning: '* 알레르기 유발 식품 : 우유',
    L_size:'414ml',
    L_sugar:'25g',
    L_protein:'12g',
    L_fat: '7g',
    L_natrium: '141mg',
    L_caffeine: '62mg',
    J_size:'473ml',
    J_sugar:'29g',
    J_protein:'14g',
    J_fat: '8g',
    J_natrium: '162mg',
    J_caffeine: '71mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 68, 
    title: '브라운슈가 쥬얼리 밀크티', 
    description: '부드럽고 달콤한 브라운 슈가 쥬얼리와 신선한 우유의 맛이 느껴지는 밀크티', 
    image: milkTea08, 
    L_price: 'Large 5,500원',
    L_kcal: '327kcal',
    warning: '* 알레르기 유발 식품 : 우유, 대두',
    L_size:'473ml',
    L_sugar:'37g',
    L_protein:'7g',
    L_fat: '7g',
    L_natrium: '160mg',
    L_caffeine: '0mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 69, 
    title: '브라운슈가 쥬얼리 밀크티 (HOT)', 
    description: '부드럽고 달콤한 브라운 슈가 쥬얼리와 신선한 우유의 맛이 느껴지는 밀크티', 
    image: milkTea08, 
    L_price: 'Large 5,500원',
    L_kcal: '435kcal',
    warning: '* 알레르기 유발 식품 : 우유, 대두',
    L_size:'473ml',
    L_sugar:'41g',
    L_protein:'11g',
    L_fat: '10g',
    L_natrium: '204mg',
    L_caffeine: '0mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 70, 
    title: '딸기 쥬얼리 밀크티', 
    description: '얼그레이티로 만든 밀크티에 리얼 딸기 과즙이 함유된 새콤달콤한 딸기 쥬얼리를 더한 음료 (딸기 함량 UP!) (ONLY ICED)', 
    image: milkTea09, 
    L_price: 'Large 5,300원',
    L_kcal: '225kcal',
    warning: '* 알레르기 유발 식품 : 우유, 대두',
    L_size:'473ml',
    L_sugar:'29g',
    L_protein:'5g',
    L_fat: '3.2g',
    L_natrium: '68mg',
    L_caffeine: '13mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
];