import newMenu01 from '../images/new_menu_01.png';
import newMenu02 from '../images/new_menu_02.png';
import newMenu03 from '../images/new_menu_03.png';
import newMenu04 from '../images/new_menu_04.png';
import newMenu05 from '../images/new_menu_05.png';
import newMenu06 from '../images/new_menu_06.png';
import newMenu07 from '../images/new_menu_07.png';
import newMenu08 from '../images/new_menu_08.png';
import newMenu09 from '../images/new_menu_09.png';
import newMenu10 from '../images/new_menu_10.png';
import newMenu11 from '../images/new_menu_11.png';
import newMenu12 from '../images/new_menu_12.png';
import newMenu13 from '../images/new_menu_13.png';
import newMenu14 from '../images/new_menu_14.png';
import newMenu15 from '../images/new_menu_15.png';
import newMenu16 from '../images/new_menu_16.png';
import newMenu17 from '../images/new_menu_17.png';
import newMenu18 from '../images/new_menu_18.png';
import newMenu19 from '../images/new_menu_19.png';
import newMenu20 from '../images/new_menu_20.png';
import newMenu21 from '../images/new_menu_21.png';
import newMenu22 from '../images/new_menu_22.png';
import newMenu23 from '../images/new_menu_23.png';
import newMenu24 from '../images/new_menu_24.png';
import newMenu25 from '../images/new_menu_25.png';
import newMenu26 from '../images/new_menu_26.png';
import newMenu27 from '../images/new_menu_27.png';
import newMenu28 from '../images/new_menu_28.png';
import newMenu29 from '../images/new_menu_29.png';
import newMenu30 from '../images/new_menu_30.png';
import newMenu31 from '../images/new_menu_31.png';
import newMenu32 from '../images/new_menu_32.png';
import newMenu33 from '../images/new_menu_33.png';
import newMenu34 from '../images/new_menu_34.png';
import newMenu35 from '../images/new_menu_35.png';
import newMenu36 from '../images/new_menu_36.png';
import newMenu37 from '../images/new_menu_37.png';
import newMenu38 from '../images/new_menu_38.png';
import newMenu39 from '../images/new_menu_39.png';
import newMenu40 from '../images/new_menu_40.png';
import newMenu41 from '../images/new_menu_41.png';

export const newMenuData = [
    { 
    id: 1, 
    title: '빠다 고구마 크림 밀크티', 
    description: '향긋한 블랙티가 들어간 단짠 솔티드 버터고구마에 고소한 타로폼과 고구마칩을 올려 달콤고소하게 즐기는 시즌한정 밀크티', 
    image: newMenu01, 
    L_price: 'Large 5,100원',
    L_kcal: '281kcal',
    warning: '알레르기 유발 식품 : 우유, 대두, 밀',
    L_size:'473ml',
    L_sugar:'24g',
    L_protein:'0g',
    L_fat: '7g',
    L_natrium: '212mg',
    L_caffeine: '28mg',
    J_size:'0',
    J_sugar:'0',
    J_protein:'0',
    J_fat: '0',
    J_natrium: '0',
    J_caffeine: '0',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 2, 
    title: '빠다 고구마 크림 밀크티 + 펄 (HOT)', 
    description: '향긋한 블랙티가 들어간 단짠 솔티드 버터고구마에 쫀득한 펄을 더하여 즐기는 시즌한정 밀크티', 
    image: newMenu01, 
    L_price: 'Large 5,100원',
    L_kcal: '282kcal',
    warning: '* 알레르기 유발 식품 : 우유, 대두, 밀',
    L_size:'414ml',
    L_sugar:'21g',
    L_protein:'6g',
    L_fat: '8g',
    L_natrium: '207mg',
    L_caffeine: '28mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 3, 
    title: '빠다 고구마 밀크티 + 펄', 
    description: '향긋한 블랙티가 들어간 단짠 솔티드 버터고구마에 쫀득한 펄을 더하여 즐기는 시즌한정 밀크티', 
    image: newMenu02, 
    L_price: 'Large 5,100원',
    L_kcal: '247kcal',
    warning: '* 알레르기 유발 식품 : 우유, 대두, 밀, 이산화황',
    L_size:'473ml',
    L_sugar:'26g',
    L_protein:'5g',
    L_fat: '3g',
    L_natrium: '117mg',
    L_caffeine: '17mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 4, 
    title: '빠다 고구마 밀크티 + 펄 (HOT)', 
    description: '향긋한 블랙티가 들어간 단짠 솔티드 버터고구마에 쫀득한 펄을 더하여 즐기는 시즌한정 밀크티', 
    image: newMenu02, 
    L_price: 'Large 5,100원',
    L_kcal: '247kcal',
    warning: '* 알레르기 유발 식품 : 우유, 대두, 밀, 이산화황',
    L_size:'414ml',
    L_sugar:'26g',
    L_protein:'6g',
    L_fat: '3g',
    L_natrium: '128mg',
    L_caffeine: '28mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 5, 
    title: '빠다 고구마 크림 밀크', 
    description: '단짠 솔티드 버터고구마에 고소한 타로폼과 고구마칩을 올려 달콤고소하게 즐기는 시즌한정 밀크', 
    image: newMenu03, 
    L_price: 'Large 5,100원',
    L_kcal: '294kcal',
    warning: '알레르기 유발 식품 : 우유, 대두, 밀',
    L_size:'473ml',
    L_sugar:'22g',
    L_protein:'7g',
    L_fat: '9g',
    L_natrium: '204mg',
    L_caffeine: '0mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 6, 
    title: '빠다 고구마 크림 밀크 (HOT)', 
    description: '단짠 솔티드 버터고구마에 고소한 타로폼과 고구마칩을 올려 달콤고소하게 즐기는 시즌한정 밀크', 
    image: newMenu03, 
    L_price: 'Large 5,100원',
    L_kcal: '283kcal',
    warning: '알레르기 유발 식품 : 우유, 대두, 밀',
    L_size:'414ml',
    L_sugar:'21g',
    L_protein:'6g',
    L_fat: '9g',
    L_natrium: '214mg',
    L_caffeine: '0mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 7, 
    title: '빠다 고구마 크림 스무디', 
    description: '향긋한 블랙티를 더한 단짠 솔티드 버터고구마에 고소한 타로폼과 고구마 칩을 올려 달콤 고소하고 시원하게 즐기는 시즌한정 스무디', 
    image: newMenu04, 
    L_price: 'Large 5,700원',
    L_kcal: '382kcal',
    warning: '알레르기 유발 식품 : 우유, 대두, 밀',
    L_size:'473ml',
    L_sugar:'31g',
    L_protein:'1g',
    L_fat: '11g',
    L_natrium: '235mg',
    L_caffeine: '28mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 8, 
    title: '초코바른 피스타치오 스무디', 
    description: '자스민티를 넣은 달콤하고 고소한 피스타치오 스무디에 바삭하게 깨지는 초코바른과 쿠키로 식감을 더한 스무디', 
    image: newMenu05, 
    L_price: 'Large 5,700원',
    L_kcal: '455kcal',
    warning: '* 알레르기 유발 식품 : 우유, 대두, 밀',
    L_size:'473ml',
    L_sugar:'38g',
    L_protein:'4g',
    L_fat: '13g',
    L_natrium: '180mg',
    L_caffeine: '21mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 9, 
    title: '초코바른 제주 그린 스무디', 
    description: '제주 녹차로 만든 스무디에 쿠키분태, 달콤짭조름한 치즈폼, 컵에 둘러진 초콜렛으로 비쥬얼을 더한 스무디​', 
    image: newMenu06, 
    L_price: 'Large 5,900원',
    L_kcal: '415kcal',
    warning: '* 알레르기 유발 식품 : 우유, 대두, 밀',
    L_size:'473ml',
    L_sugar:'40g',
    L_protein:'3g',
    L_fat: '12g',
    L_natrium: '150mg',
    L_caffeine: '75mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 10, 
    title: '초코바른 초코 스무디', 
    description: '달콤한 초코 쿠키 스무디에 달콤짭조름한 치즈폼, 컵에 둘러진 초콜렛으로 비쥬얼을 더한 스무디', 
    image: newMenu07, 
    L_price: 'Large 5,700원',
    L_kcal: '480kcal',
    warning: '알레르기 유발 식품 : 우유, 대두, 밀',
    L_size:'473ml',
    L_sugar:'26g',
    L_protein:'4g',
    L_fat: '18g',
    L_natrium: '180mg',
    L_caffeine: '15mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 11, 
    title: '피스타치오 밀크티 + 펄', 
    description: '자스민티를 넣은 달콤하고 고소한 피스타치오 밀크티에 쫀득쫀득한 펄을 더한 밀크티', 
    image: newMenu08, 
    L_price: 'Large 5,100원',
    J_price: 'Jumbo 6,200원',
    L_kcal: '320kcal',
    J_kcal: '435kcal',
    warning: '알레르기 유발 식품 : 우유, 대두, 이산화황',
    L_size:'473ml',
    L_sugar:'28g',
    L_protein:'8g',
    L_fat: '6g',
    L_natrium: '150mg',
    L_caffeine: '17mg',
    J_size:'651ml',
    J_sugar:'38g',
    J_protein:'11g',
    J_fat: '8g',
    J_natrium: '200mg',
    J_caffeine: '21ml',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    
    { 
    id: 12, 
    title: '피스타치오 밀크티 + 펄 (HOT)', 
    description: '자스민티를 넣은 달콤하고 고소한 피스타치오 밀크티에 쫀득쫀득한 펄을 더한 밀크티', 
    image: newMenu08, 
    L_price: 'Large 5,700원',
    J_price: 'Jumbo 5,900원',
    L_kcal: '355kcal',
    J_kcal: '460kcal',
    warning: '알레르기 유발 식품 : 우유, 대두, 밀',
    L_size:'414ml',
    L_sugar:'35g',
    L_protein:'9g',
    L_fat: '6g',
    L_natrium: '170mg',
    L_caffeine: '17mg',
    J_size:'473ml',
    J_sugar:'45g',
    J_protein:'12g',
    J_fat: '8g',
    J_natrium: '220mg',
    J_caffeine: '21ml',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 13, 
    title: '파인애플 코코넛 스무디', 
    description: '달콤하고 상큼한 파인패션에 고소하고 부드러운 코코넛 밀크 스무디가 들어가 한여름의 하모니를 느낄 수 있는 시즌 한정 제품', 
    image: newMenu09, 
    L_price: 'Large 5,500원',
    L_kcal: '343kcal',
    warning: '* 알레르기 유발 식품 : 우유',
    L_size:'473ml',
    L_sugar:'39g',
    L_protein:'1g',
    L_fat: '8g',
    L_natrium: '97mg',
    L_caffeine: '17.1mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 14, 
    title: '파인애플 오아시스', 
    description: '리얼 파인애플 칩이 통째로! 시원하고 고소한 코코넛 워터가 가득! 무더운 여름철 시원하고 가볍게 즐길 수 있는 카페인 프리 시즌 한정 제품', 
    image: newMenu10, 
    J_price: 'Jumbo 5,700원',
    J_kcal: '155kcal',
    J_size:'651ml',
    J_sugar:'28g',
    J_protein:'1g',
    J_fat: '0g',
    J_natrium: '47mg',
    J_caffeine: '0mg',
    isLargeAvailable: false,
    isJumboAvailable: true
    },
    { 
    id: 15, 
    title: '파인애플 오아시스 티', 
    description: '리얼 파인애플 칩이 통째로! 향긋한 자스민티와 시원하고 고소한 코코넛 워터가 가득! 무더운 여름철 시원하고 가볍게 즐길 수 있는 시즌 한정 제품', 
    image: newMenu11, 
    J_price: 'Jumbo 5,500원',
    J_kcal: '126kcal',
    J_size:'414ml',
    J_sugar:'26g',
    J_protein:'6g',
    J_fat: '3g',
    J_natrium: '128mg',
    J_caffeine: '28mg',
    isLargeAvailable: false,
    isJumboAvailable: true
    },
    { 
    id: 16, 
    title: '코코넛 밀크 스무디 + 펄', 
    description: '고소하고 부드러운 코코넛 밀크 스무디에 쫀득한 펄이 들어가 여름철 시원하게 즐길 수 있는 카페인 프리 시즌 한정 제품', 
    image: newMenu12, 
    L_price: 'Large 5,500원',
    L_kcal: '329kcal',
    warning: '* 알레르기 유발 식품 : 우유, 이산화황',
    L_size:'473ml',
    L_sugar:'32g',
    L_protein:'1g',
    L_fat: '8g',
    L_natrium: '94mg',
    L_caffeine: '0mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 17, 
    title: '코코넛 블랙 밀크티', 
    description: '고소하고 부드러운 코코넛 밀크에 진한 블랙티가 들어가 여름철 시원하게 즐길 수 있는 시즌 한정 제품', 
    image: newMenu13, 
    L_price: 'Large 4,900원',
    L_kcal: '166kcal',
    warning: '알레르기 유발 식품 : 우유',
    L_size:'473ml',
    L_sugar:'15g',
    L_protein:'4g',
    L_fat: '4g',
    L_natrium: '66mg',
    L_caffeine: '28mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 18, 
    title: '코코넛 밀크 + 미니펄', 
    description: '고소하고 부드러운 코코넛 밀크에 말랑하고 쫀득한 미니펄이 들어간 카페인 프리 시즌 한정 제품', 
    image: newMenu14, 
    L_price: 'Large 5,100원',
    L_kcal: '235kcal',
    warning: '* 알레르기 유발 식품 : 우유',
    L_size:'473ml',
    L_sugar:'21g',
    L_protein:'6g',
    L_fat: '5g',
    L_natrium: '82mg',
    L_caffeine: '0mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 19, 
    title: '납작 복숭아 아이스티 블랙 + 샷 J', 
    description: '직접 우린 향긋한 공차 티와 달콤한 납작복숭아를 더해 에스프레소 샷과 함께 달콥 쌉싸름 시원하게 즐기는 공차 아이스티', 
    image: newMenu15, 
    J_price: 'Jumbo 4,500원',
    J_kcal: '115kcal',
    J_size:'651ml',
    J_sugar:'0g',
    J_protein:'0g',
    J_fat: '0g',
    J_natrium: '3mg',
    J_caffeine: '197mg',
    isLargeAvailable: false,
    isJumboAvailable: true
    },
    { 
    id: 20, 
    title: '납작 복숭아 아이스티 얼그레이 + 샷 J', 
    description: '직접 우린 향긋한 공차 티와 달콤한 납작복숭아를 더해 에스프레소 샷과 함께 달콥 쌉싸름 시원하게 즐기는 공차 아이스티', 
    image: newMenu16, 
    J_price: 'Jumbo 4,500원',
    J_kcal: '119kcal',
    J_size:'651ml',
    J_sugar:'0g',
    J_protein:'0g',
    J_fat: '0g',
    J_natrium: '3mg',
    J_caffeine: '194mg',
    isLargeAvailable: false,
    isJumboAvailable: true
    },
    { 
    id: 21, 
    title: '납작 복숭아 아이스티 블랙 + 미니펄 J', 
    description: '직접 우린 향긋한 공차 티와 달콤한 납작복숭아를 더해 말랑쫀득 미니펄과 함께 시원하게 즐기는 공차 아이스티', 
    image: newMenu17, 
    J_price: 'Jumbo 4,700원',
    J_kcal: '216kcal',
    J_size:'651ml',
    J_sugar:'9g',
    J_protein:'0g',
    J_fat: '0g',
    J_natrium: '9mg',
    J_caffeine: '68mg',
    isLargeAvailable: false,
    isJumboAvailable: true
    },
    { 
    id: 22, 
    title: '납작 복숭아 아이스티 얼그레이 + 미니펄 J', 
    description: '직접 우린 향긋한 공차 티와 달콤한 납작복숭아를 더해 말랑쫀득 미니펄과 함께 시원하게 즐기는 공차 아이스티', 
    image: newMenu18, 
    J_price: 'Jumbo 4,700원',
    J_kcal: '220kcal',
    J_size:'651ml',
    J_sugar:'9g',
    J_protein:'1g',
    J_fat: '0g',
    J_natrium: '10mg',
    J_caffeine: '65mg',
    isLargeAvailable: false,
    isJumboAvailable: true
    },
    { 
    id: 23, 
    title: '납작 복숭아 아이스티 블랙 + 리얼 복숭아 J', 
    description: '직접 우린 향긋한 공차 티와 달콤한 납작복숭아를 더해 리얼 복숭아 원물과 함께 시원하게 즐기는 공차 아이스티', 
    image: newMenu19, 
    J_price: 'Jumbo 4,500원',
    J_kcal: '161kcal',
    J_size:'651ml',
    J_sugar:'9g',
    J_protein:'0g',
    J_fat: '0g',
    J_natrium: '7mg',
    J_caffeine: '68mg',
    isLargeAvailable: false,
    isJumboAvailable: true
    },
    { 
    id: 24, 
    title: '납작 복숭아 아이스티 얼그레이 + 리얼 복숭아 J', 
    description: '직접 우린 향긋한 공차 티와 달콤한 납작복숭아를 더해 리얼 복숭아 원물과 함께 시원하게 즐기는 공차 아이스티', 
    image: newMenu20, 
    J_price: 'Jumbo 4,500원',
    J_kcal: '165kcal',
    J_size:'651ml',
    J_sugar:'9g',
    J_protein:'1g',
    J_fat: '0g',
    J_natrium: '8mg',
    J_caffeine: '65mg',
    isLargeAvailable: false,
    isJumboAvailable: true
    },
    { 
    id: 25, 
    title: '카페 스무디 with 블랙티', 
    description: '부드러운 커피에 은은한 블랙티와 브라운슈가향이 어우러져 공차만의 스타일로 탄생한 메뉴', 
    image: newMenu21, 
    L_price: 'Large 5,200원',
    L_kcal: '259kcal',
    warning: '* 알레르기 유발 식품 : 우유',
    L_size:'473ml',
    L_sugar:'16g',
    L_protein:'2g',
    L_fat: '6g',
    L_natrium: '94mg',
    L_caffeine: '97mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 26, 
    title: '초당 옥수수 밀크티 + 펄', 
    description: '여름철 대표 간식 “초당옥수수”에 공차의 매력적인 펄과 블랙티를 더하여 시원하게 즐기는 시즌 한정 밀크티', 
    image: newMenu22, 
    L_price: 'Large 5,100원',
    L_kcal: '308kcal',
    warning: '* 알레르기 유발 식품 : 우유, 대두, 이산화황',
    L_size:'473ml',
    L_sugar:'29g',
    L_protein:'7g',
    L_fat: '4g',
    L_natrium: '182mg',
    L_caffeine: '24mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    {
    id: 27, 
    title: '미니펄 트리플 딸기 크러쉬', 
    description: '딸기를 3배로 왕창 넣어 더욱 풍성해진 미니펄 딸기 크러쉬', 
    image: newMenu23, 
    L_price: '기본 7,100원'
    },
    {
    id: 28, 
    title: '미니펄 더블 딸기 크러쉬', 
    description: '딸기를 2배로 듬뿍 넣어 더욱 풍성해진 미니펄 딸기 크러쉬', 
    image: newMenu24, 
    L_price: '기본 6,400원'
    },
    {
    id: 29, 
    title: '미니펄 트리플 망고 크러쉬', 
    description: '망고를 3배로 왕창 넣어 더욱 풍성해진 미니펄 망고 크러쉬', 
    image: newMenu25, 
    L_price: '기본 7,100원'
    },
    {
    id: 30, 
    title: '미니펄 더블 망고 크러쉬', 
    description: '망고를 2배로 듬뿍 넣어 더욱 풍성해진 미니펄 망고 크러쉬', 
    image: newMenu26, 
    L_price: '기본 6,400원'
    },
    {
    id: 31, 
    title: '미니펄 트리플 딸기 밀크티', 
    description: '딸기를 3배로 왕창 넣어 더욱 풍성해진 미니펄 딸기 밀크티', 
    image: newMenu27, 
    L_price: '기본 6,700원'
    },
    {
    id: 32, 
    title: '미니펄 더블 딸기 밀크티', 
    description: '딸기를 2배로 듬뿍 넣어 더욱 풍성해진 미니펄 딸기 밀크티', 
    image: newMenu28, 
    L_price: '기본 6,000원'
    },
    {
    id: 33, 
    title: '미니펄 트리플 망고 밀크', 
    description: '망고를 3배로 왕창 넣어 더욱 풍성해진 미니펄 망고 밀크', 
    image: newMenu29, 
    L_price: '기본 6,700원'
    },
    {
    id: 34, 
    title: '미니펄 더블 망고 밀크', 
    description: '망고를 2배로 듬뿍 넣어 더욱 풍성해진 미니펄 망고 밀크', 
    image: newMenu30, 
    L_price: '기본 6,000원'
    },
    { 
    id: 35, 
    title: '청포도 크림치즈폼', 
    description: '새콤 달콤한 청포도 음료를 산뜻하고 부드러운 크림치즈폼과 함께 시원하게 무더운 여름철에 즐길 수 있는 프룻티', 
    image: newMenu31, 
    L_price: 'Large 5,300원',
    L_kcal: '322kcal',
    warning: '* 알레르기 유발 식품 : 우유, 대두',
    L_size:'473ml',
    L_sugar:'40g',
    L_protein:'1g',
    L_fat: '7g',
    L_natrium: '170mg',
    L_caffeine: '24mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 36, 
    title: '블랙 사파이어 포도 크림치즈폼', 
    description: '달콤하게 즐길 수있는 블랙사파이어 음료를 산뜻하고 부드러운 크림치즈폼과 함께 시원하게 무더운 여름철에 즐길 수 있는 프룻티', 
    image: newMenu32, 
    L_price: 'Large 5,300원',
    L_kcal: '305kcal',
    warning: '* 알레르기 유발 식품 : 우유, 대두',
    L_size:'473ml',
    L_sugar:'37g',
    L_protein:'1g',
    L_fat: '6g',
    L_natrium: '207mg',
    L_caffeine: '85mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 37, 
    title: '꿀 복숭아 스무디', 
    description: '아삭하게 씹히는 복숭아 원물에 달콤한 꿀과 고소한 우롱티를 더해 특별하게 즐기는 시즌 한정 스무디', 
    image: newMenu33, 
    L_price: 'Large 5,300원',
    L_kcal: '344kcal',
    warning: '* 알레르기 유발 식품 : 우유, 복숭아',
    L_size:'473ml',
    L_sugar:'52g',
    L_protein:'1g',
    L_fat: '4g',
    L_natrium: '66mg',
    L_caffeine: '36mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 38, 
    title: '꿀 복숭아 밀크티', 
    description: '아삭하게 씹히는 복숭아 원물에 달콤한 꿀과 고소한 우롱티를 더해 특별하게 즐기는 시즌 한정 밀크티', 
    image: newMenu34, 
    L_price: 'Large 4,900원',
    L_kcal: '287kcal',
    warning: '* 알레르기 유발 식품 : 우유, 복숭아',
    L_size:'473ml',
    L_sugar:'42g',
    L_protein:'6g',
    L_fat: '3g',
    L_natrium: '67mg',
    L_caffeine: '40mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 39, 
    title: '꿀 복숭아 밀크', 
    description: '아삭하게 씹히는 복숭아 원물을 꿀과 함께 조화롭게 즐기는 카페인 프리 복숭아 라떼', 
    image: newMenu35, 
    L_price: 'Large 4,500원',
    L_kcal: '280kcal',
    warning: '* 알레르기 유발 식품 : 우유, 복숭아',
    L_size:'473ml',
    L_sugar:'33g',
    L_protein:'7g',
    L_fat: '4g',
    L_natrium: '81mg',
    L_caffeine: '0mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 40, 
    title: '꿀 망고 밀크', 
    description: '달콤한 망고와 꿀을 조화롭게 즐길 수 있는 카페인 프리 망고 라떼', 
    image: newMenu36, 
    L_price: 'Large 4,500원',
    L_kcal: '286kcal',
    warning: '* 알레르기 유발 식품 : 우유, 복숭아',
    L_size:'473ml',
    L_sugar:'36g',
    L_protein:'7g',
    L_fat: '5g',
    L_natrium: '84mg',
    L_caffeine: '0mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 41, 
    title: '꿀 딸기 밀크', 
    description: '상큼한 딸기와 달콤한 꿀을 조화롭게 즐길 수있는 카페인 프리 딸기 라떼', 
    image: newMenu37, 
    L_price: 'Large 4,500원',
    L_kcal: '282kcal',
    warning: '* 알레르기 유발 식품 : 우유, 대두',
    L_size:'473ml',
    L_sugar:'35g',
    L_protein:'7g',
    L_fat: '5g',
    L_natrium: '75mg',
    L_caffeine: '0mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 42, 
    title: '미니펄 망고 밀크', 
    description: '신선한 코코넛 밀크에 달콤한 애플 망고와 쫄깃한 코코넛젤리,쫀득한 미니펄까지 더해 풍성하게 즐기는 시즌 한정 음료', 
    image: newMenu38, 
    L_price: 'Large 5,300원',
    L_kcal: '271kcal',
    warning: '* 알레르기 유발 식품 : 우유',
    L_size:'473ml',
    L_sugar:'26g',
    L_protein:'7g',
    L_fat: '6g',
    L_natrium: '77mg',
    L_caffeine: '0mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 43, 
    title: '미니펄 딸기 밀크티', 
    description: '신선한 코코넛 밀크에 향긋한 얼그레이티를 블렌딩하고 상큼한 딸기 슬라이스와 쫄깃한 코코넛젤리,쫀득한 미니펄까지 더해 풍성하게 즐기는 시즌 한정 음료', 
    image: newMenu39, 
    L_price: 'Large 5,300원',
    L_kcal: '258kcal',
    warning: '* 알레르기 유발 식품 : 우유, 대두',
    L_size:'473ml',
    L_sugar:'31g',
    L_protein:'4g',
    L_fat: '4g',
    L_natrium: '53mg',
    L_caffeine: '44mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 44, 
    title: '미니펄 망고 크러쉬', 
    description: '신선한 코코넛 크러쉬에 달콤한 애플 망고와쫀득한 미니펄을 더해 특별하게 즐기는 시즌 한정 음료', 
    image: newMenu41, 
    L_price: 'Large 5,700원',
    L_kcal: '373kcal',
    warning: '* 알레르기 유발 식품 : 우유',
    L_size:'473ml',
    L_sugar:'34g',
    L_protein:'1g',
    L_fat: '9g',
    L_natrium: '94mg',
    L_caffeine: '0mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 45, 
    title: '미니펄 딸기 크러쉬', 
    description: '신선한 코코넛 크러쉬에 상큼한 딸기 슬라이스와 딸기 시럽, 쫀득한 미니펄을 더해 특별하게 즐기는 시즌 한정 음료', 
    image: newMenu40, 
    L_price: 'Large 5,700원',
    L_kcal: '386kcal',
    warning: '* 알레르기 유발 식품 : 우유, 대두',
    L_size:'473ml',
    L_sugar:'41g',
    L_protein:'1g',
    L_fat: '9g',
    L_natrium: '96mg',
    L_caffeine: '0mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
];