import tea01 from '../images/tea_01.png';
import tea02 from '../images/tea_02.png';
import tea03 from '../images/tea_03.png';
import tea04 from '../images/tea_04.png';
import tea05 from '../images/tea_05.png';
import tea06 from '../images/tea_06.png';
import tea07 from '../images/tea_07.png';
import tea08 from '../images/tea_08.png';

export const originalTeaData = [
    { 
    id: 82, 
    title: '자스민티', 
    description: '향긋한 꽃향이 느껴지는 싱그럽고 부드러운 자스민티', 
    image: tea01, 
    L_price: 'Large 4,000원',
    J_price: 'Jumbo 5,100원',
    L_kcal: '9kcal',
    J_kcal: '12kcal',
    warning: '',
    L_size:'414ml',
    L_sugar:'0g',
    L_protein:'1g',
    L_fat: '0g',
    L_natrium: '1mg',
    L_caffeine: '81mg',
    J_size:'473ml',
    J_sugar:'0g',
    J_protein:'1g',
    J_fat: '0g',
    J_natrium: '2mg',
    J_caffeine: '108mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 83, 
    title: '자스민티 (HOT)', 
    description: '향긋한 꽃향이 느껴지는 싱그럽고 부드러운 자스민티', 
    image: tea01, 
    L_price: 'Large 4,500원',
    J_price: 'Jumbo 5,600원',
    L_kcal: '7kcal',
    J_kcal: '9kcal',
    warning: '',
    L_size:'414ml',
    L_sugar:'0g',
    L_protein:'1g',
    L_fat: '0g',
    L_natrium: '3mg',
    L_caffeine: '97mg',
    J_size:'473ml',
    J_sugar:'0g',
    J_protein:'1g',
    J_fat: '0g',
    J_natrium: '4mg',
    J_caffeine: '124mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 84, 
    title: '블랙티', 
    description: '진한 향과 감미로운 맛을 느낄 수있는 대표적인 홍차, 블랙티 (HOT / ICED)​', 
    image: tea02, 
    L_price: 'Large 4,000원',
    J_price: 'Jumbo 5,100원',
    L_kcal: '8kcal',
    J_kcal: '11kcal',
    warning: '',
    L_size:'414ml',
    L_sugar:'0g',
    L_protein:'1g',
    L_fat: '0g',
    L_natrium: '1mg',
    L_caffeine: '84mg',
    J_size:'473ml',
    J_sugar:'0g',
    J_protein:'1g',
    J_fat: '0g',
    J_natrium: '2mg',
    J_caffeine: '112mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 85, 
    title: '블랙티 (HOT)', 
    description: '진한 향과 감미로운 맛을 느낄 수있는 대표적인 홍차, 블랙티 (HOT / ICED)​', 
    image: tea02, 
    L_price: 'Large 4,500원',
    J_price: 'Jumbo 5,600원',
    L_kcal: '8kcal',
    J_kcal: '9kcal',
    warning: '',
    L_size:'414ml',
    L_sugar:'0g',
    L_protein:'1g',
    L_fat: '0g',
    L_natrium: '4mg',
    L_caffeine: '100mg',
    J_size:'473ml',
    J_sugar:'0g',
    J_protein:'1g',
    J_fat: '0g',
    J_natrium: '4mg',
    J_caffeine: '128mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 86, 
    title: '블랙 스파클링 티', 
    description: '탄산이 톡톡! 청량한 탄산으로 색다르게 즐기는 진하고 감미로운 향의 블랙 스파클링 티', 
    image: tea03, 
    L_price: 'Large 5,700원',
    L_kcal: '1kcal',
    warning: '',
    L_size:'473ml',
    L_sugar:'0g',
    L_protein:'0g',
    L_fat: '0g',
    L_natrium: '3mg',
    L_caffeine: '61mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 87, 
    title: '얼그레이티', 
    description: '향긋한 베르가못향이 가미된 얼그레이티 (HOT / ICED)​', 
    image: tea04, 
    L_price: 'Large 4,000원',
    J_price: 'Jumbo 5,100원',
    L_kcal: '8kcal',
    J_kcal: '11kcal',
    warning: '',
    L_size:'414ml',
    L_sugar:'0g',
    L_protein:'1g',
    L_fat: '0g',
    L_natrium: '1mg',
    L_caffeine: '97mg',
    J_size:'473ml',
    J_sugar:'0g',
    J_protein:'1g',
    J_fat: '0g',
    J_natrium: '2mg',
    J_caffeine: '129mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 88, 
    title: '얼그레이티 (HOT)', 
    description: '향긋한 베르가못향이 가미된 얼그레이티 (HOT / ICED)​', 
    image: tea04, 
    L_price: 'Large 4,500원',
    J_price: 'Jumbo 5,600원',
    L_kcal: '8kcal',
    J_kcal: '9kcal',
    warning: '',
    L_size:'414ml',
    L_sugar:'0g',
    L_protein:'1g',
    L_fat: '0g',
    L_natrium: '3mg',
    L_caffeine: '116mg',
    J_size:'473ml',
    J_sugar:'0g',
    J_protein:'1g',
    J_fat: '0g',
    J_natrium: '4mg',
    J_caffeine: '148mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 89, 
    title: '얼그레이 스파클링 티', 
    description: '탄산이 톡톡! 청량한 탄산으로 색다르게 즐기는 향긋한 베르가못 향 얼그레이 스파클링 티', 
    image: tea05, 
    L_price: 'Large 4,300원',
    L_kcal: '1kcal',
    warning: '',
    L_size:'473ml',
    L_sugar:'0g',
    L_protein:'0g',
    L_fat: '0g',
    L_natrium: '3mg',
    L_caffeine: '45mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 90, 
    title: '우롱티', 
    description: '묵직하고 깊은 향을 간직한 고소한 우롱차 (HOT / ICED)​', 
    image: tea06, 
    L_price: 'Large 4,000원',
    J_price: 'Jumbo 5,100원',
    L_kcal: '5kcal',
    J_kcal: '7kcal',
    warning: '',
    L_size:'414ml',
    L_sugar:'0g',
    L_protein:'1g',
    L_fat: '0g',
    L_natrium: '1mg',
    L_caffeine: '65mg',
    J_size:'473ml',
    J_sugar:'0g',
    J_protein:'1g',
    J_fat: '0g',
    J_natrium: '2mg',
    J_caffeine: '86mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 91, 
    title: '우롱티 (HOT)', 
    description: '묵직하고 깊은 향을 간직한 고소한 우롱차 (HOT / ICED)​', 
    image: tea06, 
    L_price: 'Large 4,500원',
    J_price: 'Jumbo 5,600원',
    L_kcal: '5kcal',
    J_kcal: '5kcal',
    warning: '',
    L_size:'414ml',
    L_sugar:'0g',
    L_protein:'1g',
    L_fat: '0g',
    L_natrium: '3mg',
    L_caffeine: '78mg',
    J_size:'473ml',
    J_sugar:'0g',
    J_protein:'1g',
    J_fat: '0g',
    J_natrium: '4mg',
    J_caffeine: '99mg',
    isLargeAvailable: true,
    isJumboAvailable: true
    },
    { 
    id: 92, 
    title: '우롱 스파클링 티', 
    description: '탄산이 톡톡! 청량한 탄산으로 색다르게 즐기는 묵직하고 깊은 향의 우롱 스파클링 티', 
    image: tea07, 
    L_price: 'Large 5,700원',
    L_kcal: '1kcal',
    warning: '',
    L_size:'473ml',
    L_sugar:'0g',
    L_protein:'0g',
    L_fat: '0g',
    L_natrium: '2mg',
    L_caffeine: '47mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 93, 
    title: '자스민 스파클링 티', 
    description: '향긋한 꽃 향을 그대로 담은 오리지널 수제 스파클링 티', 
    image: tea08, 
    L_price: 'Large 4,300원',
    L_kcal: '2kcal',
    warning: '',
    L_size:'473ml',
    L_sugar:'0g',
    L_protein:'0g',
    L_fat: '0g',
    L_natrium: '2mg',
    L_caffeine: '60mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
] 

export default originalTeaData;