import smoothie01 from '../images/smoothie_01.png';
import smoothie02 from '../images/smoothie_02.png';
import smoothie03 from '../images/smoothie_03.png';
import smoothie04 from '../images/smoothie_04.png';
import smoothie05 from '../images/smoothie_05.png';
import smoothie06 from '../images/smoothie_06.png';
import smoothie07 from '../images/smoothie_07.png';
import smoothie08 from '../images/smoothie_08.png';
import smoothie09 from '../images/smoothie_09.png';
import smoothie10 from '../images/smoothie_10.png';
import smoothie11 from '../images/smoothie_11.png';

export const smoothieData = [
    { 
    id: 71, 
    title: '밀크 쿠앤크 스무디', 
    description: '달콤하고 바삭한 쿠키가 가득 들어간 밀크 스무디', 
    image: smoothie01, 
    L_price: 'Large 5,300원',
    L_kcal: '389kcal',
    warning: '* 알레르기 유발 식품 : 우유,밀,대두',
    L_size:'473ml',
    L_sugar:'26g',
    L_protein:'2g',
    L_fat: '14g',
    L_natrium: '167mg',
    L_caffeine: '0mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 72, 
    title: '브라운슈가 쥬얼리 치즈폼 스무디', 
    description: '부드럽고 달콤한 브라운 슈가 쥬얼리와 달콤짭조름한 치즈폼을 더한 스무디', 
    image: smoothie02, 
    L_price: 'Large 5,700원',
    L_kcal: '457kcal',
    warning: '* 알레르기 유발 식품 : 우유, 대두',
    L_size:'473ml',
    L_sugar:'45g',
    L_protein:'2g',
    L_fat: '12g',
    L_natrium: '209mg',
    L_caffeine: '0mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 73, 
    title: '딸기 쿠키 스무디', 
    description: '얼그레이티로 만든 밀크 스무디에 달콤한 딸기와 바삭한 쿠키를 더한 스무디', 
    image: smoothie03, 
    L_price: 'Large 5,700원',
    L_kcal: '446kcal',
    warning: '* 알레르기 유발 식품 : 우유, 대두, 밀',
    L_size:'473ml',
    L_sugar:'55g',
    L_protein:'3g',
    L_fat: '11g',
    L_natrium: '111mg',
    L_caffeine: '21mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 74, 
    title: '초코멜로 스무디', 
    description: '깊은 풍미의 초콜렛 스무디', 
    image: smoothie04, 
    L_price: 'Large 5,700원',
    L_kcal: '415kcal',
    warning: '* 알레르기 유발 식품 : 우유, 대두, 돼지고기',
    L_size:'473ml',
    L_sugar:'44g',
    L_protein:'5g',
    L_fat: '11g',
    L_natrium: '385mg',
    L_caffeine: '57mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 75, 
    title: '제주 그린 스무디', 
    description: '녹차가루와 부드러운 밀크폼을 함께 즐길 수 있는 제주 그린 스무디', 
    image: smoothie05, 
    L_price: 'Large 5,700원',
    L_kcal: '406kcal',
    warning: '* 알레르기 유발 식품 : 우유, 대두',
    L_size:'473ml',
    L_sugar:'40g',
    L_protein:'3g',
    L_fat: '13g',
    L_natrium: '265mg',
    L_caffeine: '88mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 76, 
    title: '청포도 스무디', 
    description: '시원달콤한 청포도과즙과 알로에 알갱이가 쏙쏙 들어오는 재미가 일품인 청포도 스무디', 
    image: smoothie06, 
    L_price: 'Large 5,700원',
    L_kcal: '255kcal',
    warning: '',
    L_size:'473ml',
    L_sugar:'50g',
    L_protein:'0g',
    L_fat: '0g',
    L_natrium: '11mg',
    L_caffeine: '10mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 77, 
    title: '망고 스무디', 
    description: '농축된 달콤한 망고와 밀크를 함께 갈아만든 망고 스무디(ONLY ICED)', 
    image: smoothie07, 
    L_price: 'Large 5,700원',
    L_kcal: '321kcal',
    warning: '* 알레르기 유발 식품 : 우유',
    L_size:'473ml',
    L_sugar:'45g',
    L_protein:'1g',
    L_fat: '6g',
    L_natrium: '64mg',
    L_caffeine: '0mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 78, 
    title: '초콜렛 쿠키&크림 스무디', 
    description: '진한 초코 스무디에 바삭한 쿠키와 밀크폼이 더해진 스무디', 
    image: smoothie08, 
    L_price: 'Large 5,300원',
    L_kcal: '406kcal',
    warning: '* 알레르기 유발 식품 : 우유, 대두, 밀',
    L_size:'473ml',
    L_sugar:'17g',
    L_protein:'4g',
    L_fat: '16g',
    L_natrium: '168mg',
    L_caffeine: '28mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 79, 
    title: '딸기 쥬얼리 요구르트 크러쉬', 
    description: '얼그레이티를 넣어 만든 요구르트 크러쉬에 리얼 딸기 과즙이 함유된 새콤달콤한 딸기 쥬얼리를 더한 음료 (ONLY ICED)', 
    image: smoothie09, 
    L_price: 'Large 5,700원',
    L_kcal: '338kcal',
    warning: '* 알레르기 유발 식품 : 우유, 대두',
    L_size:'473ml',
    L_sugar:'59g',
    L_protein:'3g',
    L_fat: '1.9g',
    L_natrium: '77mg',
    L_caffeine: '8mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 80, 
    title: '타로 스무디', 
    description: '고소한 타로가 듬뿍 들어가 진하고 달콤하게 즐길 수 있는 시즌 컴백 한정 음료', 
    image: smoothie10, 
    L_price: 'Large 4,800원',
    L_kcal: '337kcal',
    warning: '* 알레르기 유발 식품 : 우유',
    L_size:'473ml',
    L_sugar:'28g',
    L_protein:'1g',
    L_fat: '10g',
    L_natrium: '77mg',
    L_caffeine: '0mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
    { 
    id: 81, 
    title: '레몬 요구르트 스무디', 
    description: '상큼한 레몬 베이스에 달콤한 요구르트가 함께 어우려져 시원하게 즐길 수 있는 시즌 컴백 한정 음료', 
    image: smoothie11, 
    L_price: 'Large 4,800원',
    L_kcal: '294kcal',
    warning: '* 알레르기 유발 식품 : 우유, 대두',
    L_size:'473ml',
    L_sugar:'50g',
    L_protein:'2g',
    L_fat: '1g',
    L_natrium: '76mg',
    L_caffeine: '0mg',
    isLargeAvailable: true,
    isJumboAvailable: false
    },
]